CategoryMenus:
  CategoryMenu:
    isEnabled: true
    rows: 3
    title: '&c&lKategorie'
    filler-item:
      displayName: ' '
      material: 'GRAY_STAINED_GLASS_PANE'
      slots: '0-26'
    categories:
      blocks:
        material: 'GRASS_BLOCK'
        displayname: '&b&lBloki'
        lore:
          - '&ctest'
          - '&c&lDupa'
        slot: 11
        #Zalecam wprowadzić wartość taką samą jak przy displayname.
        NPC: '&b&lBloki'
        filename: 'ExampleSection.yml'