CategoryMenus:
  CategoryMenu:
    rows: 3
    title: '&c&lKategorie'
    filler-item:
      material: 'GRAY_STAINED_GLASS_PANE'
    categories:
      blocks:
        material: 'GRASS_BLOCK'
        displayname: '&b&lBloki'
        lore:
          - '&ctest'
          - '&c&lDupa'
        slot: 11
        #Zalecam wprowadzić wartość taką samą jak przy displayname.
        NPC: '&b&lBloki'
        filename: 'BlocksCategory.yml'

      items:
        material: 'NAUTILUS_SHELL'
        displayname: '&c&lPrzedmioty'
        lore:
          - 'to jest lore'
          - 'ttttttt'
        slot: 13
        NPC: 'nazwa'
        filename: 'ItemsCategory.yml'

      food:
        material: 'APPLE'
        displayname: '&c&lJedzenie'
        lore:
          - 'to jest lore'
          - 'ttttttt'
        slot: 14
        NPC: 'nazwa'
        filename: 'FoodCategory.yml'

      tools:
        material: 'IRON_PICKAXE'
        displayname: '&c&lNarzędzia'
        lore:
          - 'to jest lore'
          - 'ttttttt'
        slot: 15
        NPC: 'nazwa'
        filename: 'ToolsCategory.yml'

      redstone:
        material: 'IRON_PICKAXE'
        displayname: '&c&lRedstone'
        lore:
          - 'to jest lore'
          - 'ttttttt'
        slot: 12
        NPC: 'nazwa'
        filename: 'RedstoneCategory.yml'