categoryGUI:
  enabled: true
  displayName: '<!i><gradient:#23f2ff:#05ff0f><b>Kategorie'
  rows: 6
  elements:
    Mechanik: true
    Farmer: true
    Kowal: true
    Archeolog: true
  #You can edit these items in files for example "Mechanik.yml" in "Shops" directory

Messages:
  prefix: true
  space-in-lore: true